### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by DmitrySamoylov**
Story details: https://app.shortcut.com/lumeo/story/5604

### CODE REVIEW

**Review by FSMaxB — APPROVED** [review]
Looks good. Not sure what this has to do with `gstreamer-rs` though.

**Comment by DmitrySamoylov** [comment]
Nothing :) While upgrading `gstreamer-rs` I've upgraded `uuid` in lumeod, and it failed to compile because `api-client` wants an older `uuid::Uuid` type, so here we are.

**Comment by FSMaxB** [comment]
:thinking: Wait, the `uuid` version `1.0` doesn't work with `sqlx`, this might hurt when updating `api-client` in `api-server`.

But maybe there's a way around that. Let me do some research.

**Comment by FSMaxB** [comment]
> But maybe there's a way around that. Let me do some research.

Found a workaround! Pull-Request for `api-server` incoming!

**Pull request merged**
